// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Aliquot struct {
	ID            interface{}
	SampleID      int64
	AliquotTypeID int64
	ParentID      sql.NullInt64
	Name          string
	Description   sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
	Foreign       interface{}
}

type AliquotDisposition struct {
	ID          interface{}
	AliquotID   int64
	Disposition string
	Data        interface{}
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type AliquotType struct {
	ID          interface{}
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Box struct {
	ID          interface{}
	Name        string
	Description sql.NullString
	RackID      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Device struct {
	ID          interface{}
	Name        string
	Description sql.NullString
	LocationID  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Location struct {
	ID          interface{}
	SiteID      int64
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Rack struct {
	ID          interface{}
	Name        string
	Description sql.NullString
	ShelfID     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Sample struct {
	ID          interface{}
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   interface{}
}

type Shelf struct {
	ID          interface{}
	Name        string
	Description sql.NullString
	DeviceID    int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Site struct {
	ID          interface{}
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}
