// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package database

import (
	"context"
)

const getSample = `-- name: GetSample :one
SELECT id, name, description, created_at, updated_at FROM samples
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSample(ctx context.Context, id interface{}) (Sample, error) {
	row := q.db.QueryRowContext(ctx, getSample, id)
	var i Sample
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSamples = `-- name: ListSamples :many
SELECT id, name, description, created_at, updated_at FROM samples
ORDER BY id
`

func (q *Queries) ListSamples(ctx context.Context) ([]Sample, error) {
	rows, err := q.db.QueryContext(ctx, listSamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sample
	for rows.Next() {
		var i Sample
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
