[build]
dockerfilePath = "Dockerfile"
dockerBuildTarget = "production"

[deploy]
preDeployCommand = "uv run python /app/krill/manage.py migrate"
startCommand = "uv run gunicorn --workers 3 --timeout 120 krill.wsgi:application"
healthcheckPath = "/login/"
healthcheckTimeout = 30
