# Generated by Django 5.0.1 on 2026-03-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_permission_options_alter_userrole_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('import', 'Import'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('role_changed', 'Role Changed'), ('password_changed', 'Password Changed'), ('sample_created', 'Sample Created'), ('sample_updated', 'Sample Updated'), ('sample_deleted', 'Sample Deleted'), ('aliquot_created', 'Aliquot Created'), ('aliquot_updated', 'Aliquot Updated')], max_length=20),
        ),
    ]
