# Generated by Django 5.0.1 on 2025-08-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_userpreference_created_at_userpreference_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditlog',
            name='target_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
