# Generated by Django 5.0.1 on 2025-08-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_userauditlog_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditlog',
            name='target_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
