# Generated by Django 5.0.1 on 2025-08-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_userauditlog_target_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='lab_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
