# Generated by Django 5.0.1 on 2025-08-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_alter_userrole_department_alter_userrole_lab_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
