# Generated by Django 5.0.1 on 2025-09-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('storage', 'Storage'), ('sample', 'Sample'), ('system', 'System'), ('security', 'Security'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='target_id',
            field=models.IntegerField(blank=True, help_text='ID of the object this alert relates to', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='target_type',
            field=models.CharField(blank=True, help_text='Type of object this alert relates to', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path to generated file', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_size',
            field=models.IntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('excel', 'Excel')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Parameters used to generate this report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='result_data',
            field=models.JSONField(blank=True, default=dict, help_text='Generated report data'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('sample_inventory', 'Sample Inventory'), ('storage_capacity', 'Storage Capacity'), ('user_activity', 'User Activity'), ('aliquot_tracking', 'Aliquot Tracking'), ('custom', 'Custom Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='template_data',
            field=models.JSONField(default=dict, help_text='JSON configuration for the report template'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Default parameters for the report'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='recipients',
            field=models.JSONField(default=list, help_text='List of email addresses to receive the report'),
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
