# Generated by Django 5.0.1 on 2025-09-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_issue_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('sample_inventory', 'Sample Inventory'), ('storage_capacity', 'Storage Capacity'), ('user_activity', 'User Activity'), ('aliquot_tracking', 'Aliquot Tracking'), ('storage_audit', 'Storage Audit'), ('custom', 'Custom Report')], max_length=50),
        ),
    ]
