# Generated by Django 5.0.1 on 2025-02-19 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliquotDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dispositionType', models.CharField(choices=[('stored', 'Stored'), ('exhausted', 'Exhausted'), ('in_use', 'In Use')], default='stored', max_length=32)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AliquotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('row', models.PositiveSmallIntegerField(default=1)),
                ('column', models.PositiveSmallIntegerField(default=1)),
                ('passage', models.CharField(default=0, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.box')),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.aliquotdisposition')),
                ('aliquotType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.aliquottype')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.sample')),
            ],
        ),
    ]
