# Generated by Django 5.0.1 on 2025-02-22 02:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliquotDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dispositionType', models.CharField(choices=[('stored', 'Stored'), ('exhausted', 'Exhausted'), ('in_use', 'In Use')], default='stored', max_length=32)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AliquotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experiment', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('passage', models.CharField(default=0, max_length=200)),
                ('experiment', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.aliquot')),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.aliquotdisposition')),
                ('aliquotType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.aliquottype')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.sample')),
            ],
        ),
        migrations.CreateModel(
            name='AliquotLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('column', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('aliquot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.aliquot')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.box')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.source'),
        ),
    ]
