# Generated by Django 5.0.1 on 2025-08-31 23:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliquotDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('dispositionType', models.CharField(choices=[('stored', 'Stored'), ('exhausted', 'Exhausted'), ('in_use', 'In Use')], default='stored', max_length=32)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AliquotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experiment', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Number of test tubes in this aliquot')),
                ('passage', models.CharField(default=0, max_length=200)),
                ('experiment', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.aliquot')),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.aliquotdisposition')),
                ('aliquotType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.aliquottype')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.sample')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.source'),
        ),
        migrations.CreateModel(
            name='AliquotLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('column', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tube_number', models.PositiveSmallIntegerField(default=1, help_text='Tube number within this aliquot (1, 2, 3, etc.)')),
                ('aliquot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.aliquot')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.box')),
            ],
            options={
                'unique_together': {('aliquot', 'tube_number'), ('box', 'row', 'column')},
            },
        ),
        migrations.CreateModel(
            name='AliquotTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tube_number', models.PositiveSmallIntegerField(help_text='Tube number within this aliquot (1, 2, 3, etc.)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aliquot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.aliquot')),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.aliquotdisposition')),
            ],
            options={
                'unique_together': {('aliquot', 'tube_number')},
            },
        ),
    ]
