# Generated by Django 5.0.1 on 2025-09-01 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliquot',
            name='disposition',
        ),
    ]
