# Generated by Django 5.0.1 on 2025-02-19 04:41

from django.db import migrations

def insert_aliquot_dispositions(apps, schema_editor):
    AliquotDisposition = apps.get_model('sample', 'AliquotDisposition')
    stored = AliquotDisposition(name="Stored", dispositionType="Stored", description="Aliquot is currently stored")
    exhausted = AliquotDisposition(name="Exhausted", dispositionType="Exhausted", description="Aliquot is exhausted")
    in_use = AliquotDisposition(name="In Use", dispositionType="In Use", description="Aliquot is currently in use")

    stored.save()
    exhausted.save()
    in_use.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_aliquot_dispositions),
    ]
