# Generated by Django 5.0.1 on 2025-11-06 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_remove_aliquot_aliquottype_remove_aliquot_experiment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aliquot',
            options={'ordering': ['sample__name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['name']},
        ),
    ]
