# Generated by Django 5.0.1 on 2025-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_alter_aliquot_experiment_alter_aliquot_notes_and_more'),
        ('storage', '0003_device_auto_store_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliquotlocation',
            name='tube_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Tube number within this aliquot (1, 2, 3, etc.)'),
        ),
        migrations.AlterField(
            model_name='aliquot',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Number of test tubes in this aliquot'),
        ),
        migrations.AlterUniqueTogether(
            name='aliquotlocation',
            unique_together={('aliquot', 'tube_number'), ('box', 'row', 'column')},
        ),
    ]
