# Generated by Django 5.0.1 on 2026-04-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_aliquot_redesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliquot',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
