# Generated by Django 5.0.1 on 2025-08-31 22:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_aliquotlocation_tube_number_alter_aliquot_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliquotTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tube_number', models.PositiveSmallIntegerField(help_text='Tube number within this aliquot (1, 2, 3, etc.)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aliquot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.aliquot')),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.aliquotdisposition')),
            ],
            options={
                'unique_together': {('aliquot', 'tube_number')},
            },
        ),
    ]
