# Generated by Django 5.0.1 on 2025-11-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['user__username', 'permission_type'], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['user__username'], 'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('import', 'Import'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('role_changed', 'Role Changed'), ('password_changed', 'Password Changed')], max_length=20),
        ),
    ]
