# Generated by Django 5.0.1 on 2025-09-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='access_level',
            field=models.CharField(choices=[('admins_only', 'Admins Only'), ('admins_managers', 'Admins & Managers'), ('all_members', 'All Lab Members')], default='all_members', help_text='Restrict access to specific user tiers', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='access_level',
            field=models.CharField(choices=[('admins_only', 'Admins Only'), ('admins_managers', 'Admins & Managers'), ('all_members', 'All Lab Members')], default='all_members', help_text='Restrict access to specific user tiers', max_length=20),
        ),
        migrations.AddField(
            model_name='rack',
            name='access_level',
            field=models.CharField(choices=[('admins_only', 'Admins Only'), ('admins_managers', 'Admins & Managers'), ('all_members', 'All Lab Members')], default='all_members', help_text='Restrict access to specific user tiers', max_length=20),
        ),
        migrations.AddField(
            model_name='shelf',
            name='access_level',
            field=models.CharField(choices=[('admins_only', 'Admins Only'), ('admins_managers', 'Admins & Managers'), ('all_members', 'All Lab Members')], default='all_members', help_text='Restrict access to specific user tiers', max_length=20),
        ),
    ]
