# Generated by Django 5.0.1 on 2024-12-15 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': 'boxes'},
        ),
        migrations.AlterModelOptions(
            name='shelf',
            options={'verbose_name_plural': 'shelves'},
        ),
    ]
