# Generated by Django 5.0.1 on 2025-08-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_box_description_alter_device_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='auto_store_enabled',
            field=models.BooleanField(default=False, help_text='Enable auto-store for all boxes in this device'),
        ),
    ]
