# Generated by Django 5.0.1 on 2026-06-14 22:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('antibody', 'Antibody'), ('enzyme', 'Enzyme'), ('kit', 'Kit'), ('chemical', 'Chemical/Reagent'), ('cell_line', 'Cell Line'), ('plasmid', 'Plasmid'), ('oligo', 'Oligo/Primer'), ('plasticware', 'Plasticware'), ('media', 'Media/Buffer'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('spec_schema', models.JSONField(blank=True, default=list)),
                ('icon', models.CharField(blank=True, default='category', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('cabinet', 'Cabinet'), ('shelf', 'Shelf'), ('fridge', 'Refrigerator'), ('freezer', 'Freezer'), ('bench', 'Bench'), ('other', 'Other')], default='shelf', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='consumables.consumableroom')),
            ],
            options={
                'ordering': ['room__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('catalog_number', models.CharField(blank=True, max_length=120, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=120, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(default='units', max_length=30)),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('access_level', models.CharField(choices=[('admins_only', 'Admins Only'), ('admins_managers', 'Admins & Managers'), ('all_members', 'All Lab Members')], default='all_members', help_text='Restrict access to specific user tiers', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='consumables.consumablelocation')),
                ('consumable_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumables', to='consumables.consumabletype')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumables', to='consumables.vendor')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='consumablelocation',
            index=models.Index(fields=['room', 'name'], name='consumables_room_id_0a7f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['consumable_type'], name='consumables_consuma_770754_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['location'], name='consumables_locatio_b9ed50_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['deleted', 'name'], name='consumables_deleted_a3924e_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['catalog_number'], name='consumables_catalog_7ea8c7_idx'),
        ),
    ]
